version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.7.3
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip



jobs:
  test_regression_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Intsall requirements
          command: |
            . venv/bin/activate
            pip install -r packages/regression_model/requirements.txt
      
      - run:
          name: Run Test
          command: |
              . venv/bin/activate
              py.test -vv packages/regression_model/tests
  
  
  test_ml_api:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Testing api
          command: |
            . venv/bin/activate
            pip install -r packages/ml_api/requirements.txt
            py.test -vv packages/regression_model/tests
  
  train_and_publish_regression_model:
    <<: *defaults
    steps:
        - checkout
        - *prepare_venv
        - run:
            name: install requirements
            command: |  
                . venv/bin/activate
                pip install -r packages/regression_model/requirements.txt
        - run:
            name: Train model 
            command: |
                . venv/bin/activate
                PYTHONPATH=./packages/regression_model python3 ./packages/regression_model/regression_model/train_pipeline.py
        - run:
            name: publish model
            command: |
              . venv/bin/activate
              chmod +x ./scripts/publish_model.sh
              ./scripts/publish_model.sh ./packages/regression_model






workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
      - test_ml_api
      - train_and_publish_regression_model:
          requires:
            - test_regression_model
            - test_ml_api
