version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
            py.test -vv packages/regression_model/tests
  
  
  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Testing api
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_api/requirements.txt
            py.test -vv packages/regression_model/tests
  
  train_and_publish_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.3
    steps:
        - checkout
        - run:
            name: Setup
            command: |
                virtualenv venv  
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r packages/regression_model/requirements.txt
        - run:
            name: Train and publish 
            command: |
                . venv/bin/activate
                chmod +x ./scripts/publish_model.sh
                PYTHONPATH=./packages/regression_model python3 ./packages/regression_model/regression_model/train_pipeline.py
                ./scripts/publish_model.sh ./packages/regression_model



workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
      - test_ml_api
      - train_and_publish_regression_model
      - test_ml_api:
          requires:
           - train_and_publish_regression_model